Fixed throwing an error with anonymous users
elchris/FOSOAuthServerBundle pull request #5
Opened 2020-02-19 15:55 UTC by patrickbussmann

I now had the situation that I want to deliver a function to anonymous users.
And then I'm wondering why I always get this `Token for event was null` error - until I find out that the original repository returns nothing there while this symfony-5 implementation throws an exception.

So I added a test for anonymous users and fixed the problem.

If there is another sense for this throwing logic exception you can explain me how I can enable anonymous users - because the user is only anonymous when all authentications are returning null = AnonymousToken instead OAuthToken

2020-02-19 15:56 UTC, patrickbussmann commented
Now it work's: @elchris 
https://github.com/FriendsOfSymfony/FOSOAuthServerBundle/issues/625

Here is the pull request.

2020-02-24 16:39 UTC, patrickbussmann commented
Can you merge this please? @elchris

2020-02-24 16:41 UTC, elchris requested changes

2020-02-24 16:41 UTC, elchris commented on Security/Firewall/OAuthListener.php
>          }
Just to keep things clean, do you think that you could avoid having the "return" as the "handle" method's return type is "void" so it's technically not supposed to "return". It looks like when the token is null you just want to "do nothing", in which case you might be able to "invert the if" such that the new token gets created only of the oauthToken is not null.

@patrickbussmann what do you think?

And I really like that you made a test to capture this use-case. Thank you for this! :)

2020-02-24 16:42 UTC, elchris commented
> Can you merge this please? @elchris

yes can you please look at [this](https://github.com/elchris/FOSOAuthServerBundle/pull/5#discussion_r381420670) first?

2020-02-24 16:44 UTC, merged

2020-02-24 16:45 UTC, elchris commented
> > Can you merge this please? @elchris
> 
> yes can you please look at [this](https://github.com/elchris/FOSOAuthServerBundle/pull/5#discussion_r381420670) first?

I merged it anyway

2020-02-24 16:45 UTC, patrickbussmann commented
Ah ok but yes I could change this. Sorry I didnt get the message 😣

2020-02-24 16:51 UTC, elchris commented
> Ah ok but yes I could change this. Sorry I didnt get the message 😣

no worries, it looks like I'd forgotten to "submit the review", my bad hehe.

Can you pull from my fork again, because I merged other changes that touched the same file, and look at that method again and submit another PR with the fix if needed